apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
        labels:
          app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        resources:
          limits:
            memory: "500Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-lb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 31050
  selector:
    app: mongo
  type: LoadBalancer
status:
  loadBalancer: {}
